<script>
    function mascaraData(campo, e) {
        var kC = (document.all) ? event.keyCode : e.keyCode;
        var data = campo.value;

        if (kC != 8 && kC != 46) {
            if (data.length == 2) {
                campo.value = data += '/';
            } else if (data.length == 5) {
                campo.value = data += '/';
            } else
                campo.value = data;
        }
    }
</script>
<div class="row d-flex justify-content-center my-3">
    <div class="col-md-8 col-12 text-center border-bottom">
        <h4>Listagem de movimentação</h4>
    </div>
</div>

<div class="row">

    <div class="col-12 col-md-12 d-flex justify-content-center px-4">
        <form action="/admin/extracts/listagem/filtro" method="POST" class="mb-2">
            <div class="input-inline">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <a href="/admin/extracts/listagem" class="btn btn-dark" title="Limpar"><i class="fas fa-eraser text-white" title="Limpar"></i></a>
                    </div>
                    <select name="tipo_movimentacao" id="tipo_movimentacao" class="form-control">
                        <option disabled selected class="form-control">Tipo</option>
                        <option value="entrada" class="form-control">Entrada</option>
                        <option value="saida" class="form-control">Saída</option>
                    </select>

                    <input type="text" name="nome_funcionario" class="form-control" placeholder="Nome" value="<?= $this->view->nomeFunc ?>">
                    <input type="text" name="data_criacao" class="form-control" placeholder="Data criação" value="<?= $this->view->dataCriacao ?>" maxlength="10" onkeypress="mascaraData( this, event )">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-info">
                            <i class="fas fa-filter"></i>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row d-flex justify-content-center mt-2">
    <div class="col-12 col-md-10">
        <table class="table table-striped mx-2" id="tabelas">
            <thead class="thead-dark rounded-top">
                <tr  class="text-center">
                    <th scope="col">id</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Valor</th>
                    <th scope="col" style="width:250px;">Observacao</th>
                    <th scope="col">Funcionário</th>
                    <th scope="col" class="d-none d-md-block">Data de criação</th>
                </tr>
            </thead>
            <tbody>
                <?php if (isset($this->view->msgError)) { ?>
                    <div class="alert alert-danger  alert-dismisseble" role="alert">
                        <button class="close" type="button" data-dismiss="alert">
                            &times;
                        </button> <?= $this->view->msgError  ?>
                    </div>
                    <?php } else {
                    $tot = 0;
                    $qtd = $this->view->extratos['encontrados'];

                    while ($tot < $qtd) { ?>
                        <tr scope="row"  class="text-center">

                            <td><?= $this->view->extratos['data'][$tot]['id'] ?></td>
                            <td><?= $this->view->extratos['data'][$tot]['tipo_movimentacao'] ?></td>
                            <td>R$ <?= number_format($this->view->extratos['data'][$tot]['valor'], 2, ',', '.') ?></td>
                            <td><?= $this->view->extratos['data'][$tot]['observacao'] ?></td>
                            <td><?= $this->view->extratos['data'][$tot]['nome_completo'] ?></td>
                            <?php $data_criacao = date('d-m-Y', strtotime($this->view->extratos['data'][$tot]['data_criacao'])); ?>
                            <td class="d-none d-md-block"><?= str_replace("-", "/", $data_criacao) ?></td>
                        </tr>
                <?php
                        $tot++;
                    }
                }
                ?>
            </tbody>
        </table>
    </div>
</div>

<div class="row my-4">
    <div class="col-12 col-md-10 d-flex justify-content-md-end justify-content-center">

        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <?php
                $counter = 1;
                $pages = $this->view->extratos['pages'];
                if($qtd > 0){
                do {
                ?>
                    <li class="page-item">
                        <a class="page-link" href="/admin/extracts/listagem?page=<?= $counter ?>"><?= $counter ?></a>
                    </li>
                <?php
                    $counter++;
                } while ($counter <= $pages); }else{?>

                    <li class="page-item">
                        <a class="page-link" href="/admin/extracts/listagem">0</a>
                    </li>
                <?php } ?>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>

        </nav>

    </div>
</div>